name: Run Linter

description: Run Linter

runs:
  using: composite
  steps:
    - name: Setup Repo
      uses: ./.github/actions/ci/setup

    - name: Run Linter
      uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
      with:
        version: v2.12.2
        args: --config=.github/actions/ci/lint/golangci.yml
